const runAgenticSwarm = require('./agents/agentOrchestrator');
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const PORT=process.env.PORT||3000, ROOT=path.join(__dirname,'public');
const sessions=new Map();
const users=[{id:'analyst-001',role:'analyst',username:'admin',password:'admin123',name:'Junior Analyst'},{id:'member-10001',role:'member',username:'astra10001',password:'pass10001',name:'Kavya Verma',account:'ASTR00010001',state:'Tamil Nadu',kyc:'Verified ✔',phone:'+91 98765 43210',bal:'2,45,800.00',risk:'Low risk'}];
const caseSeed=[
{id:'AB-000117',name:'Kavya Verma',tag:'Rapid beneficiary + transfer burst',risk:96,signals:['5 high-value transfers / 5 days','New beneficiary added','Cross-state movement','Unusual hours (03:14 AM)'],why:'New beneficiary followed by multiple high-value transfers across states and unusual hours.',device:'DEV_77A',city:'Bengaluru',beneficiary:'ACC_LAYER_HQ'},
{id:'AB-000305',name:'Rohan Sharma',tag:'Single inbound festival refund spike',risk:22,signals:['Single inbound credit','Known retail gateway','Low-risk / reviewed','Trusted hardware node'],why:'Large transaction volume matched a known merchant festival refund pattern; no sustained anomaly detected.',device:'DEV_18C',city:'Chennai',beneficiary:'MERCHANT_REFUND'},
{id:'AB-000642',name:'Harish Rao',tag:'Hardware ID reuse & rapid outbound drain',risk:88,signals:['DEV_MULE_X (4 users)','ACC_LAYER_HQ','₹3,40,000 in 20 min','Mule ring layering'],why:'Suspect hardware device DEV_MULE_X registered across four accounts in 12 hours with immediate fund funneling.',device:'DEV_MULE_X',city:'Hyderabad',beneficiary:'ACC_LAYER_HQ'},
{id:'AB-000721',name:'Amit Patel',tag:'Odd-hour anomaly',risk:85,signals:['Out-of-hours transfer','₹92,000 at 03:15 AM','Mumbai IP','Unregistered device'],why:'Transaction amount is significantly above the user historical median and occurred in a high-risk time window.',device:'DEV_NEW_91',city:'Mumbai',beneficiary:'BEN_441'},
{id:'AB-000889',name:'Priya Jain',tag:'Micro-transaction flood',risk:78,signals:['Rapid identical micro-transactions','14 attempts / 90 sec','New browser fingerprint','Velocity anomaly'],why:'Rapid identical micro-transactions are consistent with automated testing of stolen account details.',device:'DEV_BOT_14',city:'Delhi',beneficiary:'BEN_992'}];
const caseState=new Map(caseSeed.map(c=>[c.id,{...c,status:'OPEN'}]));
const kb=[{id:'KB-01',title:'Account takeover signals',text:'Account takeover investigations commonly correlate unusual login time, new device, geographic deviation, beneficiary changes and velocity spikes. A single signal should not automatically trigger a freeze.'},{id:'KB-02',title:'Mule-account patterns',text:'Mule rings can show device reuse across accounts, rapid outbound transfers, shared beneficiaries and short-lived balances. Correlation across entities is more informative than isolated transactions.'},{id:'KB-03',title:'Human-in-the-loop controls',text:'High-risk fraud decisions should remain reviewable by an authorized analyst. The swarm prepares evidence and recommendations; the human decision gate records freeze or release.'},{id:'KB-04',title:'Privacy-preserving risk sharing',text:'A commitment can bind hidden attributes without putting the raw attributes in the analyst-facing record. A commitment is not by itself a formal zero-knowledge proof.'}];
function tok(){return crypto.randomBytes(24).toString('hex')} function send(res,code,obj){const b=Buffer.from(JSON.stringify(obj));res.writeHead(code,{'Content-Type':'application/json','Content-Length':b.length,'Access-Control-Allow-Origin':'*'});res.end(b)} function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){resolve({})}});req.on('error',reject)})}
function auth(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/,'');return sessions.get(t)}
function customer(i){const n=['Kavya Verma','Rohan Sharma','Harish Rao','Amit Patel','Priya Jain','Arjun Nair','Meera Iyer','Rahul Singh','Ananya Rao','Vikram Das'];const id=String(i).padStart(5,'0');return{id:`CUST-${id}`,name:n[i%10],username:`astra${10000+i}`,password:`pass${10000+i}`,account:`ASTR${id}`,state:['Tamil Nadu','Karnataka','Maharashtra','Telangana','Delhi'][i%5],kyc:i%7===0?'PENDING':'VERIFIED',phone:`+91 90000 ${String(10000+i).slice(-5)}`,bal:(75000+(i*1379)%600000).toLocaleString('en-IN',{minimumFractionDigits:2}),risk:i%53===0?'High risk':'Low risk'}}
function rows(){const a=[];for(let i=1;i<=1000;i++)a.push({id:i,amount:1000+(i*791)%120000,hour:(i*7)%24,newBeneficiary:i%53===0,deviceReuse:i%97===0?4:1,velocity:i%41===0?7:1,device:i%97===0?'DEV_MULE_X':`DEV_${i%80}`,city:['Chennai','Bengaluru','Mumbai','Hyderabad','Delhi'][i%5],beneficiary:i%53===0?'BEN_NEW':`BEN_${i%300}`});return a}
function scout(rs){return rs.map(r=>{let score=0,s=[];if(r.amount>=75000){score+=28;s.push('high-value transfer')}if(r.hour<5||r.hour>=23){score+=25;s.push('odd-hour activity')}if(r.newBeneficiary){score+=20;s.push('new beneficiary')}if(r.deviceReuse>=3){score+=30;s.push('device reuse')}if(r.velocity>=5){score+=22;s.push('velocity spike')}return score>=45?{...r,score,signals:s}:null}).filter(Boolean)}
function runSwarm() {
    const transactions = rows();

    return runAgenticSwarm(transactions);
}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex')}
async function api(req,res,u){const p=u.pathname,m=req.method;if(p==='/api/health')return send(res,200,{ok:true,service:'Astra Sentinel API',version:'1.0.0'});
 if(p==='/api/auth/analyst'&&m==='POST'){const b=await body(req),x=users.find(x=>x.role==='analyst'&&x.username===b.username&&x.password===b.password);if(!x)return send(res,401,{error:'Invalid analyst credentials'});const t=tok();sessions.set(t,{userId:x.id,role:x.role,name:x.name});return send(res,200,{token:t,user:{id:x.id,role:x.role,name:x.name}})}
 if(p==='/api/auth/member'&&m==='POST'){const b=await body(req);let x=users.find(x=>x.role==='member'&&x.username===b.username&&x.password===b.password);if(!x&&/^astra\d+$/.test(b.username)){const i=+b.username.slice(5)-10000;if(i>=1&&i<=1000){const c=customer(i);if(c.username===b.username&&c.password===b.password)x={...c,role:'member'}}}if(!x)return send(res,401,{error:'Invalid member credentials'});const t=tok();sessions.set(t,{userId:x.id,role:'member',name:x.name});return send(res,200,{token:t,user:{id:x.id,role:x.role,name:x.name,username:x.username,password:x.password,account:x.account,state:x.state,kyc:x.kyc,phone:x.phone||'+91 90000 00000',bal:x.bal||'75,000.00',risk:x.risk||'Low risk'}})}
 const s=auth(req);if(!s)return send(res,401,{error:'Unauthorized'});
 if(p==='/api/auth/logout'&&m==='POST'){sessions.delete((req.headers.authorization||'').replace(/^Bearer\s+/,''));return send(res,200,{ok:true})}
 if(p==='/api/cases'&&m==='GET'){if(s.role!=='analyst')return send(res,403,{error:'Analyst only'});return send(res,200,{cases:[...caseState.values()]})}
 if(p==='/api/customers'&&m==='GET'){if(s.role!=='analyst')return send(res,403,{error:'Analyst only'});const q=(u.searchParams.get('q')||'').toLowerCase(),out=[];for(let i=1;i<=1000&&out.length<100;i++){const c=customer(i);if(!q||Object.values(c).some(v=>String(v).toLowerCase().includes(q)))out.push(c)}return send(res,200,{total:1000,customers:out})}
 if(p==='/api/swarm/run'&&m==='POST'){if(s.role!=='analyst')return send(res,403,{error:'Analyst only'});return send(res,200,runSwarm())}
 const cm=p.match(/^\/api\/cases\/([^/]+)\/action$/);if(cm&&m==='POST'){if(s.role!=='analyst')return send(res,403,{error:'Analyst only'});const c=caseState.get(cm[1]),b=await body(req);if(!c)return send(res,404,{error:'Case not found'});if(!['freeze','release'].includes(b.action))return send(res,400,{error:'Action must be freeze or release'});c.status=b.action==='freeze'?'FROZEN':'RELEASED';c.actionBy=s.name;c.actionAt=new Date().toISOString();return send(res,200,{ok:true,case:c})}
 if(p==='/api/passport/create'&&m==='POST'){const b=await body(req);if(!b.riskBand||!b.region||!b.tenureMonths||!b.secret)return send(res,400,{error:'Missing passport fields'});const nonce=crypto.randomBytes(16).toString('hex'),commitment=hash(JSON.stringify({riskBand:b.riskBand,region:b.region,tenureMonths:b.tenureMonths,secret:b.secret,nonce}));return send(res,200,{passportId:`ZKP-${crypto.randomBytes(4).toString('hex').toUpperCase()}`,commitment,nonce,claims:{riskBand:b.riskBand,region:b.region,tenureMonths:b.tenureMonths},note:'Commitment-based privacy prototype. Not a formal zero-knowledge proof system.'})}
 if(p==='/api/passport/verify'&&m==='POST'){const b=await body(req);const ok=!!(b.riskBand&&b.region&&b.tenureMonths&&b.secret&&b.nonce&&b.commitment)&&hash(JSON.stringify({riskBand:b.riskBand,region:b.region,tenureMonths:b.tenureMonths,secret:b.secret,nonce:b.nonce}))===b.commitment;return send(res,200,{verified:ok,commitment:b.commitment,disclosure:ok?'Claims match the original commitment.':'Commitment mismatch; claims were not verified.'})}
 if(p==='/api/rag/search'&&m==='POST'){const b=await body(req),q=String(b.query||'').toLowerCase(),terms=q.split(/\s+/).filter(Boolean),r=kb.map(d=>({d,score:terms.reduce((n,t)=>n+(d.title.toLowerCase().includes(t)?3:0)+(d.text.toLowerCase().includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);return send(res,200,{query:q,results:r.map(x=>({...x.d,score:x.score}))})}
 return send(res,404,{error:'Not found'});
}
const server=http.createServer(async(req,res)=>{const u=url.parse(req.url,true);if(u.pathname.startsWith('/api/'))return api(req,res,u);let file=u.pathname==='/'?'/index.html':u.pathname;file=path.normalize(file).replace(/^\.\.(\/|\\)/,'');const fp=path.join(ROOT,file);if(!fp.startsWith(ROOT)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory())return send(res,404,{error:'Not found'});const ext=path.extname(fp);const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(fp).pipe(res)});
server.listen(PORT,()=>console.log(`Astra Bank Sentinel running at http://localhost:${PORT}`));
